
project_id = "juzawihlfesurtewxgdy"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "https://localhost:3000",
  "https://juzawihlfesurtewxgdy.supabase.co/auth/v1/callback",
  "http://localhost:3000",
  "https://*.lovableproject.com/auth/callback",
  "https://*.lovableproject.com/"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.external.apple]
enabled = true
client_id = "your.app.bundle.id"
secret = ""
# Add any additional Apple-specific parameters if needed
additional_provider_parameters = { response_mode = "form_post" }

[auth.external.google]
enabled = true
client_id = "435056018915-s4ut4m4sf1muj60eagpnoqatnh4kvl8u.apps.googleusercontent.com"
secret = "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"
# Additional params to prevent cookies issues
additional_provider_parameters = { access_type = "offline", prompt = "consent" }

[functions]
[functions.send-email]
verify_jwt = true
