
project_id = "juzawihlfesurtewxgdy"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions]
[functions.secure-file-access]
verify_jwt = true

[functions.secure-encrypt]
verify_jwt = true

[functions.audit-log]
verify_jwt = true

[analytics]
enabled = false
