
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Only focus on production dependencies for security updates
    open-pull-requests-limit: 10
    versioning-strategy: auto
    labels:
      - "dependencies"
      - "security"
    ignore:
      # Ignore dev dependencies
      - dependency-name: "@types/*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
    commit-message:
      prefix: "deps"
      include: "scope"
    
