
services:
  - type: web
    name: express-server
    env: node
    plan: free
    buildCommand: bun install && bun run build
    startCommand: node src/server/start-server.cjs
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
