
services:
  - type: web
    name: job-seekers-4-high-schools
    buildCommand: yarn install && yarn build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=86400
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /lovable-uploads/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /lovable-uploads/*-*w.jpg
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /lovable-uploads/*-*w.png
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /lovable-uploads/*-*w.webp
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /lovable-uploads/*-*w.avif
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /api/*
        name: Cache-Control
        value: public, max-age=1800, stale-while-revalidate=86400
      - path: /*
        name: Vary
        value: Accept-Encoding

staticSites:
  - name: job-seekers-static
    buildCommand: yarn build
    publishDir: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=86400
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /lovable-uploads/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /lovable-uploads/*-*w.jpg
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /lovable-uploads/*-*w.png
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /lovable-uploads/*-*w.webp
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /lovable-uploads/*-*w.avif
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*
        name: Vary
        value: Accept-Encoding
