
services:
  - type: web
    name: jobseekaroo  # Changed from express-server to match your app
    env: node
    plan: free
    branch: main
    rootDir: ""  # Repo root, where index.html lives
    buildCommand: npm install && npm run build
    startCommand: node src/server/start-server.cjs
    envVars:
      - key: PORT
        value: 8080  # Render default, optional
      - key: SUPABASE_URL
        sync: false  # Add in dashboard
      - key: SUPABASE_KEY
        sync: false  # Add in dashboard
