
services:
  - type: web
    name: express-server
    env: node
    buildCommand: npm install && npm run build
    startCommand: node start-prod.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
