
services:
  - type: web
    name: express-server
    env: node
    buildCommand: bun install && bun run build
    startCommand: node src/server/start-server.cjs
    envVars:
      - key: PORT
        value: 3000
