
services:
  - type: web
    name: job-seekers-4-high-schools
    buildCommand: yarn install && yarn build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production

staticSites:
  - name: job-seekers-static
    buildCommand: yarn build
    publishDir: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
