
import { Job } from '../../types/job';

export const mockJobs: Job[] = [
  {
    id: '1',
    title: 'Retail Sales Associate',
    company: 'Jacksonville Electronics',
    location: {
      city: 'Jacksonville',
      state: 'FL',
      zipCode: '32256',
    },
    type: 'part-time',
    payRate: {
      min: 15,
      max: 18,
      period: 'hourly',
    },
    description: 'Join our retail team helping customers find the perfect electronics. Learn about the latest technology while developing valuable customer service and sales skills.',
    requirements: [
      'No prior experience required',
      'Interest in technology and electronics',
      'Strong communication skills',
      'Availability for weekend shifts',
    ],
    experienceLevel: 'entry-level',
    postedDate: '2023-09-15',
    logoUrl: 'https://images.unsplash.com/photo-1563770660941-10b3dc965c00?ixlib=rb-4.0.3&auto=format&fit=crop&w=120&q=80',
    isRemote: false,
    isFlexible: true,
  },
  {
    id: '2',
    title: 'IT Help Desk Apprentice',
    company: 'TechSolutions Jacksonville',
    location: {
      city: 'Jacksonville',
      state: 'FL',
      zipCode: '32204',
    },
    type: 'apprenticeship',
    payRate: {
      min: 16,
      max: 19,
      period: 'hourly',
    },
    description: 'Exciting opportunity to start your IT career with our structured apprenticeship program. Learn technical support, troubleshooting, and customer service skills while earning.',
    requirements: [
      'High school diploma or equivalent',
      'Basic computer knowledge',
      'Eagerness to learn IT concepts',
      'Strong problem-solving abilities',
    ],
    experienceLevel: 'entry-level',
    postedDate: '2023-09-10',
    logoUrl: 'https://images.unsplash.com/photo-1633419461186-7d40a38105ec?ixlib=rb-4.0.3&auto=format&fit=crop&w=120&q=80',
    isRemote: false,
    isFlexible: false,
  },
  {
    id: '3',
    title: 'Office Assistant',
    company: 'River City Legal',
    location: {
      city: 'Jacksonville',
      state: 'FL',
      zipCode: '32202',
    },
    type: 'part-time',
    payRate: {
      min: 15,
      max: 17,
      period: 'hourly',
    },
    description: 'Entry-level position supporting our legal office with administrative tasks, filing, client communication, and basic data entry. Great opportunity to learn about the legal field.',
    requirements: [
      'High school diploma or equivalent',
      'Basic computer skills',
      'Professional demeanor',
      'Detail-oriented mindset',
    ],
    experienceLevel: 'entry-level',
    postedDate: '2023-09-12',
    logoUrl: 'https://images.unsplash.com/photo-1556741533-6e6a62bd8b49?ixlib=rb-4.0.3&auto=format&fit=crop&w=120&q=80',
    isRemote: false,
    isFlexible: true,
  },
  {
    id: '4',
    title: 'Healthcare Receptionist',
    company: 'Jacksonville Medical Center',
    location: {
      city: 'Jacksonville',
      state: 'FL',
      zipCode: '32216',
    },
    type: 'full-time',
    payRate: {
      min: 16,
      max: 18,
      period: 'hourly',
    },
    description: 'Join our healthcare team as a front desk receptionist, welcoming patients, scheduling appointments, and handling basic administrative duties in a fast-paced medical environment.',
    requirements: [
      'High school diploma required',
      'Customer service experience preferred but not required',
      'Excellent communication and interpersonal skills',
      'Basic computer proficiency',
    ],
    experienceLevel: 'entry-level',
    postedDate: '2023-09-08',
    logoUrl: 'https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?ixlib=rb-4.0.3&auto=format&fit=crop&w=120&q=80',
    isRemote: false,
    isFlexible: false,
  },
  {
    id: '5',
    title: 'Electrical Apprentice',
    company: 'Jacksonville Electric',
    location: {
      city: 'Jacksonville',
      state: 'FL',
      zipCode: '32207',
    },
    type: 'apprenticeship',
    payRate: {
      min: 17,
      max: 21,
      period: 'hourly',
    },
    description: 'Paid apprenticeship program to learn the electrical trade under experienced professionals. Gain hands-on skills in residential and commercial electrical installation and repair.',
    requirements: [
      'High school diploma or GED',
      'Reliable transportation',
      'Physical ability to lift 50+ pounds',
      'Interest in electrical work and willingness to learn',
    ],
    experienceLevel: 'entry-level',
    postedDate: '2023-09-05',
    logoUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?ixlib=rb-4.0.3&auto=format&fit=crop&w=120&q=80',
    isRemote: false,
    isFlexible: false,
  },
  {
    id: '6',
    title: 'Veterinary Assistant Trainee',
    company: 'Jacksonville Animal Care',
    location: {
      city: 'Jacksonville',
      state: 'FL',
      zipCode: '32225',
    },
    type: 'part-time',
    payRate: {
      min: 15,
      max: 18,
      period: 'hourly',
    },
    description: 'Learn to assist veterinarians with animal care in our entry-level position. Help with patient handling, exam room preparation, and basic medical support under supervision.',
    requirements: [
      'High school diploma',
      'Love of animals',
      'Able to work in fast-paced environment',
      'Willingness to learn veterinary procedures',
    ],
    experienceLevel: 'entry-level',
    postedDate: '2023-09-03',
    logoUrl: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?ixlib=rb-4.0.3&auto=format&fit=crop&w=120&q=80',
    isRemote: false,
    isFlexible: true,
  },
  {
    id: '7',
    title: 'Banking Associate Trainee',
    company: 'First Jacksonville Bank',
    location: {
      city: 'Jacksonville',
      state: 'FL',
      zipCode: '32202',
    },
    type: 'full-time',
    payRate: {
      min: 17,
      max: 19,
      period: 'hourly',
    },
    description: 'Start your career in financial services. This entry-level position provides comprehensive training in customer service, banking products, and financial transactions.',
    requirements: [
      'High school diploma required',
      'Basic math skills',
      'Professional appearance',
      'Strong customer service orientation',
    ],
    experienceLevel: 'entry-level',
    postedDate: '2023-09-02',
    logoUrl: 'https://images.unsplash.com/photo-1601597111158-2fceff292cdc?ixlib=rb-4.0.3&auto=format&fit=crop&w=120&q=80',
    isRemote: false,
    isFlexible: false,
  },
  {
    id: '8',
    title: 'Carpentry Apprentice',
    company: 'Jacksonville Builders',
    location: {
      city: 'Jacksonville',
      state: 'FL',
      zipCode: '32254',
    },
    type: 'apprenticeship',
    payRate: {
      min: 16,
      max: 20,
      period: 'hourly',
    },
    description: 'Learn the carpentry trade from the ground up in our structured apprenticeship program. Gain skills in woodworking, construction, and finishing while earning a competitive wage.',
    requirements: [
      'High school diploma or equivalent',
      'Valid driver\'s license',
      'Ability to lift 50+ pounds',
      'Reliable transportation to job sites',
    ],
    experienceLevel: 'entry-level',
    postedDate: '2023-09-01',
    logoUrl: 'https://images.unsplash.com/photo-1598521145507-ea8659fd087a?ixlib=rb-4.0.3&auto=format&fit=crop&w=120&q=80',
    isRemote: false,
    isFlexible: false,
  },
  {
    id: '9',
    title: 'Hotel Front Desk Trainee',
    company: 'Jacksonville Waterfront Hotel',
    location: {
      city: 'Jacksonville',
      state: 'FL',
      zipCode: '32202',
    },
    type: 'part-time',
    payRate: {
      min: 15,
      max: 17,
      period: 'hourly',
    },
    description: 'Entry-level position at our upscale hotel. Learn hospitality operations including check-in/out procedures, reservation management, and delivering exceptional guest service.',
    requirements: [
      'High school diploma',
      'Customer service aptitude',
      'Availability for evening and weekend shifts',
      'Professional appearance',
    ],
    experienceLevel: 'entry-level',
    postedDate: '2023-08-28',
    logoUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=120&q=80',
    isRemote: false,
    isFlexible: true,
  },
  {
    id: '10',
    title: 'HVAC Apprentice',
    company: 'Cool Air Solutions',
    location: {
      city: 'Jacksonville',
      state: 'FL',
      zipCode: '32246',
    },
    type: 'apprenticeship',
    payRate: {
      min: 17,
      max: 22,
      period: 'hourly',
    },
    description: 'Join our paid apprenticeship program to learn HVAC installation, maintenance, and repair. Work alongside experienced technicians in residential and commercial settings.',
    requirements: [
      'High school diploma or GED',
      'Valid driver\'s license',
      'Basic mechanical aptitude',
      'Ability to work in various weather conditions',
    ],
    experienceLevel: 'entry-level',
    postedDate: '2023-08-25',
    logoUrl: 'https://images.unsplash.com/photo-1680595382543-0741ac55a054?ixlib=rb-4.0.3&auto=format&fit=crop&w=120&q=80',
    isRemote: false,
    isFlexible: false,
  },
];
