import { Job } from '@/types/job';

// Update the location property in jobs to use 'zip' instead of 'zipCode'
export const healthcareJobs: Job[] = [
  {
    id: '1',
    title: 'Registered Nurse',
    company_name: 'Mayo Clinic',
    company: {
      name: 'Mayo Clinic',
      logoUrl: '/logos/mayo-clinic.png',
    },
    logo_url: '/logos/mayo-clinic.png',
    description: 'Provide direct patient care, administer medications, and monitor vital signs.',
    job_type: 'full-time',
    experience_level: 'mid-level',
    location: {
      city: 'Jacksonville',
      state: 'FL',
      zip: '32202'  // Changed from zipCode to zip
    },
    is_remote: false,
    pay_rate_min: 65000,
    pay_rate_max: 90000,
    pay_rate_period: 'yearly',
    hours_per_week: 40,
    is_flexible: false,
    requirements: ['Valid RN license', 'BLS certification', 'Excellent communication skills'],
    posted_date: '2024-01-20',
    created_at: '2024-01-20',
    updated_at: '2024-01-20',
    is_teen_appropriate: false,
  },
  {
    id: '2',
    title: 'Medical Assistant',
    company_name: 'Baptist Health',
    company: {
      name: 'Baptist Health',
      logoUrl: '/logos/baptist-health.png',
    },
    logo_url: '/logos/baptist-health.png',
    description: 'Assist physicians with clinical and administrative tasks, including taking patient histories and vital signs.',
    job_type: 'full-time',
    experience_level: 'entry-level',
    location: {
      city: 'Jacksonville',
      state: 'FL',
      zip: '32207'  // Changed from zipCode to zip
    },
    is_remote: false,
    pay_rate_min: 35000,
    pay_rate_max: 45000,
    pay_rate_period: 'yearly',
    hours_per_week: 40,
    is_flexible: false,
    requirements: ['High school diploma', 'Medical assistant certification', 'CPR certification'],
    posted_date: '2024-01-15',
    created_at: '2024-01-15',
    updated_at: '2024-01-15',
    is_teen_appropriate: false,
  },
  {
    id: '3',
    title: 'Physical Therapist',
    company_name: 'Brooks Rehabilitation',
    company: {
      name: 'Brooks Rehabilitation',
      logoUrl: '/logos/brooks-rehab.png',
    },
    logo_url: '/logos/brooks-rehab.png',
    description: 'Evaluate and treat patients with musculoskeletal and neurological conditions to improve mobility and function.',
    job_type: 'full-time',
    experience_level: 'mid-level',
    location: {
      city: 'Jacksonville',
      state: 'FL',
      zip: '32216'  // Changed from zipCode to zip
    },
    is_remote: false,
    pay_rate_min: 70000,
    pay_rate_max: 100000,
    pay_rate_period: 'yearly',
    hours_per_week: 40,
    is_flexible: true,
    requirements: ['Physical therapy license', 'CPR certification', 'Strong manual therapy skills'],
    posted_date: '2024-01-10',
    created_at: '2024-01-10',
    updated_at: '2024-01-10',
    is_teen_appropriate: false,
  },
  {
    id: '4',
    title: 'Certified Nursing Assistant (CNA)',
    company_name: 'Ascension St. Vincent\'s',
    company: {
      name: 'Ascension St. Vincent\'s',
      logoUrl: '/logos/ascension.png',
    },
    logo_url: '/logos/ascension.png',
    description: 'Assist patients with daily living activities and provide basic nursing care under the supervision of a registered nurse.',
    job_type: 'part-time',
    experience_level: 'entry-level',
    location: {
      city: 'Jacksonville',
      state: 'FL',
      zip: '32204'  // Changed from zipCode to zip
    },
    is_remote: false,
    pay_rate_min: 14,
    pay_rate_max: 18,
    pay_rate_period: 'hourly',
    hours_per_week: 20,
    is_flexible: true,
    requirements: ['CNA certification', 'High school diploma', 'Compassionate and caring attitude'],
    posted_date: '2024-01-05',
    created_at: '2024-01-05',
    updated_at: '2024-01-05',
    is_teen_appropriate: false,
  },
  {
    id: '5',
    title: 'Pharmacy Technician',
    company_name: 'Walgreens',
    company: {
      name: 'Walgreens',
      logoUrl: '/logos/walgreens.png',
    },
    logo_url: '/logos/walgreens.png',
    description: 'Assist pharmacists with dispensing medications, managing inventory, and providing customer service.',
    job_type: 'full-time',
    experience_level: 'entry-level',
    location: {
      city: 'Jacksonville',
      state: 'FL',
      zip: '32210'  // Changed from zipCode to zip
    },
    is_remote: false,
    pay_rate_min: 15,
    pay_rate_max: 20,
    pay_rate_period: 'hourly',
    hours_per_week: 40,
    is_flexible: false,
    requirements: ['High school diploma', 'Pharmacy technician certification', 'Excellent customer service skills'],
    posted_date: '2023-12-28',
    created_at: '2023-12-28',
    updated_at: '2023-12-28',
    is_teen_appropriate: false,
  },
  {
    id: '6',
    title: 'Medical Receptionist',
    company_name: 'Cleveland Clinic',
    company: {
      name: 'Cleveland Clinic',
      logoUrl: '/logos/cleveland-clinic.png',
    },
    logo_url: '/logos/cleveland-clinic.png',
    description: 'Greet patients, schedule appointments, and handle phone calls in a medical office setting.',
    job_type: 'full-time',
    experience_level: 'entry-level',
    location: {
      city: 'Jacksonville',
      state: 'FL',
      zip: '32224'  // Changed from zipCode to zip
    },
    is_remote: false,
    pay_rate_min: 14,
    pay_rate_max: 17,
    pay_rate_period: 'hourly',
    hours_per_week: 40,
    is_flexible: false,
    requirements: ['High school diploma', 'Excellent communication skills', 'Customer service experience'],
    posted_date: '2023-12-20',
    created_at: '2023-12-20',
    updated_at: '2023-12-20',
    is_teen_appropriate: false,
  },
  {
    id: '7',
    title: 'Dental Hygienist',
    company_name: 'Aspen Dental',
    company: {
      name: 'Aspen Dental',
      logoUrl: '/logos/aspen-dental.png',
    },
    logo_url: '/logos/aspen-dental.png',
    description: 'Provide dental care services, including cleaning teeth and educating patients on oral hygiene.',
    job_type: 'full-time',
    experience_level: 'mid-level',
    location: {
      city: 'Jacksonville',
      state: 'FL',
      zip: '32256'  // Changed from zipCode to zip
    },
    is_remote: false,
    pay_rate_min: 60000,
    pay_rate_max: 80000,
    pay_rate_period: 'yearly',
    hours_per_week: 35,
    is_flexible: true,
    requirements: ['Dental hygiene license', 'CPR certification', 'Excellent communication skills'],
    posted_date: '2023-12-15',
    created_at: '2023-12-15',
    updated_at: '2023-12-15',
    is_teen_appropriate: false,
  },
  {
    id: '8',
    title: 'Optometrist',
    company_name: 'Visionworks',
    company: {
      name: 'Visionworks',
      logoUrl: '/logos/visionworks.png',
    },
    logo_url: '/logos/visionworks.png',
    description: 'Examine, diagnose, and treat visual defects and eye diseases.',
    job_type: 'full-time',
    experience_level: 'senior-level',
    location: {
      city: 'Jacksonville',
      state: 'FL',
      zip: '32217'  // Changed from zipCode to zip
    },
    is_remote: false,
    pay_rate_min: 90000,
    pay_rate_max: 120000,
    pay_rate_period: 'yearly',
    hours_per_week: 40,
    is_flexible: false,
    requirements: ['Doctor of Optometry degree', 'Optometry license', 'Strong diagnostic skills'],
    posted_date: '2023-12-10',
    created_at: '2023-12-10',
    updated_at: '2023-12-10',
    is_teen_appropriate: false,
  },
  {
    id: '9',
    title: 'Medical Coder',
    company_name: 'UnitedHealth Group',
    company: {
      name: 'UnitedHealth Group',
      logoUrl: '/logos/unitedhealth.png',
    },
    logo_url: '/logos/unitedhealth.png',
    description: 'Assign codes to diagnoses and procedures for billing and insurance purposes.',
    job_type: 'full-time',
    experience_level: 'mid-level',
    location: {
      city: 'Jacksonville',
      state: 'FL',
      zip: '32211'  // Changed from zipCode to zip
    },
    is_remote: true,
    pay_rate_min: 45000,
    pay_rate_max: 60000,
    pay_rate_period: 'yearly',
    hours_per_week: 40,
    is_flexible: true,
    requirements: ['Medical coding certification', 'Knowledge of ICD-10 and CPT codes', 'Attention to detail'],
    posted_date: '2023-12-05',
    created_at: '2023-12-05',
    updated_at: '2023-12-05',
    is_teen_appropriate: false,
  },
  {
    id: '10',
    title: 'Healthcare Administrator',
    company_name: 'HCA Healthcare',
    company: {
      name: 'HCA Healthcare',
      logoUrl: '/logos/hca.png',
    },
    logo_url: '/logos/hca.png',
    description: 'Plan, direct, and coordinate medical and health services in a healthcare facility.',
    job_type: 'full-time',
    experience_level: 'senior-level',
    location: {
      city: 'Jacksonville',
      state: 'FL',
      zip: '32216'  // Changed from zipCode to zip
    },
    is_remote: false,
    pay_rate_min: 80000,
    pay_rate_max: 110000,
    pay_rate_period: 'yearly',
    hours_per_week: 40,
    is_flexible: false,
    requirements: ['Bachelor\'s degree in healthcare administration', '5+ years of experience', 'Strong leadership skills'],
    posted_date: '2023-11-28',
    created_at: '2023-11-28',
    updated_at: '2023-11-28',
    is_teen_appropriate: false,
  },
];
