
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://juzawihlfesurtewxgdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1emF3aWhsZmVzdXJ0ZXd4Z2R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NzY2MTQsImV4cCI6MjA1ODA1MjYxNH0.Nr03z5g2dRPGOsDHSqrpkmdsZnBdlpXRlOpRBBIApIA";

// Import the supabase client like this:
// import { supabase } from "@/lib/supabase";
// Or directly from this file:
// import { supabaseClient } from "@/integrations/supabase/client";

export const supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Legacy compatibility export
export const supabase = supabaseClient;
